- hosts: all
  connection: local
  vars:
    slaves:
      - distribution: "Ubuntu"
        version: "12.04"
        image: "ami-2ccc7a44"
        ssh_user: "ubuntu"
        platform: "ubuntu-12.04-x86_64"
      - distribution: "Ubuntu"
        version: "14.04"
        image: "ami-9a562df2"
        ssh_user: "ubuntu"
        platform: "ubuntu-14.04-x86_64"
      - distribution: "CentOS"
        version: "6.5"
        image: "ami-8997afe0"
        ssh_user: "root"
        platform: "centos-6.5-x86_64"
      - distribution: "CentOS"
        version: "7"
        image: "ami-96a818fe"
        ssh_user: "centos"
        platform: "centos-7-x86_64"
          
  tasks:
    - debug: var=ansible_version
    - include: ec2.yml
      when: groups['dynamic_hosts'] is not defined

- hosts: dynamic_hosts
  sudo: true
  vars:
    credentials_file: ''
    test_flags: ""
    make_target: "non_destructive"
  pre_tasks:
    - name: Sync ansible repo to ec2 instance
      synchronize: 
        src: "{{ sync_dir }}/"
        dest: "~/ansible"
  roles:
    - { role: install_deps, tags: install_deps }
    - { role: run_integration, tags: run_integration }
  tasks:
    - name: Kill ec2 instances
      sudo: false
      local_action:
        module: ec2
        state: absent
        region: 'us-east-1'
        instance_ids: "{{ hostvars[item]['ec2_instance_ids'] }}"
      with_items: groups['dynamic_hosts']

    - fail:
        msg: "{{ test_results }}"
      when: "test_results.rc != 0"
