---
- name: Install RH epel
  yum: name="epel-release" state=installed
  sudo: true
  when: ansible_os_family == 'RedHat'

- name: Install RH ansible dependencies
  yum: name="{{ item }}" state=installed
  sudo: true
  with_items:
    - python-pip
    - python-httplib2
    - rsync
    - subversion
    - mercurial
    - git
    - rubygems
    - unzip
    - openssl
    - make
    - gcc
    - python-devel
    - libselinux-python
  when: ansible_os_family == 'RedHat'

- apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Install Debian ansible dependencies
  apt: name="{{ item }}" state=installed update_cache=yes
  sudo: true
  with_items:
    - python-pip
    - python-httplib2
    - rsync
    - subversion
    - mercurial
    - git
    - unzip
  when: ansible_os_family == 'Debian'

- name: Install ubuntu 12.04 ansible dependencies
  apt: name="{{ item }}" state=installed update_cache=yes
  sudo: true
  with_items:
    - rubygems
    - python-devel
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "12.04"

- name: Install ubuntu 14.04 ansible dependencies
  apt: name="{{ item }}" state=installed update_cache=yes
  sudo: true
  with_items:
    - rubygems-integration
    - python-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "14.04"

- name: Install ansible pip deps
  sudo: true
  pip: name="{{ item }}"
  with_items:
    - PyYAML
    - Jinja2
    - paramiko

