---
- name: Sync ansible repo to ec2 instance
  synchronize: 
    src: "{{ sync_dir }}/"
    dest: "~/ansible"

- name: Get ansible source dir
  sudo: false
  shell: "cd ~ && pwd"
  register: results

- shell: ". hacking/env-setup && cd test/integration && make {{ run_integration_make_target }}"
  sudo: true
  environment:
    TEST_FLAGS: "{{ run_integration_test_flags|default(lookup('env', 'TEST_FLAGS')) }}"
    CREDENTIALS_FILE: "{{ run_integration_credentials_file|default(lookup('env', 'CREDENTIALS_FILE')) }}"
  args:
    chdir: "{{ results.stdout }}/ansible"
  register: test_results
  ignore_errors: true
